# Generated by Django 5.0.6 on 2024-06-22 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_usercustom_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercustom',
            name='course',
        ),
        migrations.AlterField(
            model_name='usercustom',
            name='niveau',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
