# Generated by Django 5.0.6 on 2024-06-22 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0002_course_alter_coursedetail_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='chapitre',
            new_name='lesson',
        ),
        migrations.DeleteModel(
            name='CourseDetail',
        ),
    ]
