# Generated by Django 5.0.6 on 2024-06-22 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0003_rename_chapitre_course_lesson_delete_coursedetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='course',
            old_name='lesson',
            new_name='chapitre',
        ),
    ]
