# Generated by Django 5.0.6 on 2024-06-21 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0002_course_alter_coursedetail_course'),
        ('Positioning', '0001_initial'),
        ('accounts', '0002_alter_usercustom_course'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
