# Generated by Django 5.0.6 on 2024-06-27 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Positioning', '0003_userscore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userscore',
            name='score',
        ),
        migrations.AddField(
            model_name='userscore',
            name='niveau',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
